# Generated by Django 3.2.19 on 2023-06-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230622_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='artby',
            field=models.CharField(default='', max_length=20),
        ),
    ]
